[package]
name = "ariel-os-mountain-mqtt"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["mqtt", "embassy"]
categories = [
  "asynchronous",
  "embedded",
  "network-programming",
  "no-std::no-alloc",
  "encoding",
]
description = "A no_std compatible, async MQTT v5 client for arielos, using mountain-mqtt"

[dependencies]
ariel-os-debug-log = { workspace = true }
ariel-os-utils = { workspace = true }
ariel-os-embassy = { workspace = true }

embassy-sync.workspace = true

heapless = { workspace = true }
embassy-time = { workspace = true }
embassy-net = { version = "0.8.0", features = [
  "tcp",
  "udp",
  "raw",
  "dhcpv4",
  "medium-ethernet",
  "dns",
] }

embassy-futures = { workspace = true }

defmt = { workspace = true, optional = true }

log = { workspace = true, optional = true }

embedded-io-async = { version = "0.7.0" }

mountain-mqtt = { workspace = true, default-features = false, features = [
  "embedded-io-async",
  "embedded-hal-async",
] }

[features]

defmt = [
  "dep:defmt",
  "embassy-net/defmt",
  "embassy-sync/defmt",
  "embedded-io-async/defmt",
  "mountain-mqtt/defmt",
]

log = ["dep:log", "embassy-net/log", "embassy-sync/log"]
