[package]
name = "mqtt-performance-test"
license.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = ["udp", "tcp", "usb", "external-interrupts", "mqtt", "mountain-mqtt"] }

# mountain-mqtt = { path = "./mountain-mqtt", default-features = false, features = [
#   "embedded-io-async",
#   "embedded-hal-async"
# ] }
# mountain-mqtt-arielos = { path = "./mountain-mqtt-arielos"}

serde = { version = "1.0.209", default-features = false, features = ["derive"] }
serde-json-core = "0.6.0"

static_cell.workspace = true

embassy-sync.workspace = true
embassy-futures.workspace = true
embassy-net.workspace = true
heapless.workspace = true