[package]
name = "mqtt-sn-performance-test-sender"
license.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = ["udp", "external-interrupts", "mqttsn", "defmt"] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }

#[dev-dependencies]
#embedded-test = { workspace = true }
#
#[[bin]]
#name = "mqtt-sn-client"
#harness = false
